### ISSUE TITLE
Bottom corners issue

### ISSUE THREAD

**Issue by edpil02** [paulmcauley/classik#11]
When I increase the radius of the windows decorations  to get rounded corners,  the bottom corners are not quite round.
Looks like there are square and round corners overlapping at the same time. 
Thanks.
![Screenshot_20211228_162816](https://user-images.githubusercontent.com/43163048/147582473-39be6138-b9f4-4074-9f5e-bcccad6a42f1.png)

**Comment by paulmcauley** [comment]
You need to increase your border size in the Wibdiw Deciration configuration menu to accommodate a larger corner radius. The square area belongs to the application, and, by design, the window decoration's rounded corners will not steal any space that belongs to the application.

If you want to subtract some of the application's corner you can try effects such as https://github.com/matinlotfali/KDE-Rounded-Corners but I have not tried it myself as I don't think the application's area should ever be reduced for a rounded corner.
